### ISSUE TITLE
Add GitHub CI Workflow

### ISSUE THREAD

**Issue by gflohr** [gflohr/einvoice-eu#63]

**Comment by flipswitchingmonkey** [comment]
This one works nicely: https://github.com/flipswitchingmonkey/e-invoice-eu/blob/main/.github/workflows/docker-publish.yml

It pushes to the github docker repo, but could of course push to dockerhub as well

**Comment by gflohr** [comment]
This is very much appreciated. Can you open a PR?

I must admit that the Docker stuff is not my forte. I currently push OCI images to dockerhub manually with my personal account, see https://hub.docker.com/repository/docker/gflohr/e-invoice-eu/general. I am totally open to improvements.

**Comment by gflohr** [comment]
My idea was to have an `e-invoice-eu:latest` image for every release or push and an `e-invoice-eu:VERSION` for every release. Whatever comes close to that is probably better than my current approach.

**Comment by flipswitchingmonkey** [comment]
here you go https://github.com/gflohr/e-invoice-eu/pull/64

**Comment by gflohr** [comment]
Thanks a lot! Merged! I will try that out with the next release.

**Comment by gflohr** [comment]
Thanks again! It worked like a charm! https://hub.docker.com/repository/docker/gflohr/e-invoice-eu/tags/v1.3.0/sha256-cdf3f4f7188a8fd63d8f59bff59712357e95104c0c7f2794c3392ab2b22b3e03

That saves a lot of work for me. :)
